pipelines:
  branches:
    master:
    - step:
        image: node:lts-alpine3.19
        script:
          - npm cache clean --force
          - npm install --force
          - npm run build:prod
    - step:
        name: Deploy to ECR
        trigger: manual
        script:
         - docker build -t swr-ui:latest .

         - pipe: atlassian/aws-ecr-push-image:2.3.0
           variables:
            IMAGE_NAME: swr-ui
            TAGS: latest



            
            
