pipelines:
  branches:
    master:
    - step:
        name: Deploy to ECR
        script:
         - docker build -t swr-ui:latest .

         - pipe: atlassian/aws-ecr-push-image:2.3.0
           variables:
            IMAGE_NAME: swr-ui
            TAGS: latest



            
            
