image: node:14.16.0

pipelines:
  branches:
    master:
    - step:
        name: Deploy to ECR
        trigger: manual
        script:
         - docker build -t swr-ui:latest .

         - pipe: atlassian/aws-ecr-push-image:2.3.0
           variables:
            AWS_DEFAULT_REGION: 'eu-central-1'
            IMAGE_NAME: swr-ui
            TAGS: latest



            
            
